# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Digital Design implementation codes/UART Project/pynq_transmitter/pynq_transmitter.cache/wt} [current_project]
set_property parent.project_path {D:/Digital Design implementation codes/UART Project/pynq_transmitter/pynq_transmitter.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {D:/Digital Design implementation codes/Pynq_project/mod_counter.v}
  {D:/Digital Design implementation codes/Pynq_project/UART_Transmitter.v}
  {D:/Digital Design implementation codes/Pynq_project/baud_rate_gen.v}
  {D:/Digital Design implementation codes/Pynq_project/UART_sys.v}
}
read_xdc {{D:/Digital Design implementation codes/UART Project/pynq_transmitter/pynq_transmitter.srcs/constrs_1/new/UART_sys.xdc}}
set_property used_in_implementation false [get_files {{D:/Digital Design implementation codes/UART Project/pynq_transmitter/pynq_transmitter.srcs/constrs_1/new/UART_sys.xdc}}]

read_xdc {{D:/Digital Design implementation codes/Pynq_project/PYNQ-Z1_C.xdc}}
set_property used_in_implementation false [get_files {{D:/Digital Design implementation codes/Pynq_project/PYNQ-Z1_C.xdc}}]

synth_design -top UART_sys -part xc7z020clg400-1
write_checkpoint -noxdef UART_sys.dcp
catch { report_utilization -file UART_sys_utilization_synth.rpt -pb UART_sys_utilization_synth.pb }
