webtalk_init -webtalk_dir D:/Digital Design implementation codes/UART Project/UART Communication Protocol/UART Communication Protocol.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 14 04:41:09 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1215546" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "36bd4464-017c-4321-b46f-4b4b21c29fe8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cf4c65f5-216e-48f3-97e8-ff3c4897ab41" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A4-5000 APU with Radeon(TM) HD Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1497 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1293491911 -regid "" -xml D:/Digital Design implementation codes/UART Project/UART Communication Protocol/UART Communication Protocol.hw/webtalk/usage_statistics_ext_labtool.xml -html D:/Digital Design implementation codes/UART Project/UART Communication Protocol/UART Communication Protocol.hw/webtalk/usage_statistics_ext_labtool.html -wdm D:/Digital Design implementation codes/UART Project/UART Communication Protocol/UART Communication Protocol.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
