######################################################################
#
# File name : Baudrate_Generator_wave.do
# Created on: Tue Feb 12 02:18:46 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
