######################################################################
#
# File name : Baudrate_Generator_compile.do
# Created on: Tue Feb 12 02:18:33 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"./../../../../Baudrate_Generator.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

