######################################################################
#
# File name : UART_Receiver_simulate.do
# Created on: Thu Feb 14 02:04:18 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -t 1ps -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.UART_Receiver xil_defaultlib.glbl

do {UART_Receiver_wave.do}

view wave
view structure
view signals

do {UART_Receiver.udo}

run 1000ns
