######################################################################
#
# File name : UART_Transmitter_elaborate.do
# Created on: Tue Feb 12 04:09:56 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

quit -force
