######################################################################
#
# File name : UART_Receiver_compile.do
# Created on: Thu Feb 14 02:04:13 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"./../../../../UART_Receiver.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

