######################################################################
#
# File name : UART_Transmitter.udo
# Created on: Tue Feb 12 02:21:46 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
