######################################################################
#
# File name : UART_Transmitter_simulate.do
# Created on: Tue Feb 12 04:09:58 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -t 1ps -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.UART_Transmitter xil_defaultlib.glbl

do {UART_Transmitter_wave.do}

view wave
view structure
view signals

do {UART_Transmitter.udo}

run 1000ns
