######################################################################
#
# File name : UART_Transmitter_elaborate.do
# Created on: Wed Feb 20 15:21:10 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

quit -force
