######################################################################
#
# File name : UART_Receiver_wave.do
# Created on: Thu Feb 14 02:04:18 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
