######################################################################
#
# File name : UART_Transmitter_compile.do
# Created on: Wed Feb 20 15:21:08 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"./../../../../UART_Transmitter.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

