######################################################################
#
# File name : UART_Transmitter_wave.do
# Created on: Wed Feb 20 15:21:12 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
