######################################################################
#
# File name : UART_Receiver.udo
# Created on: Thu Feb 14 01:28:10 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
