######################################################################
#
# File name : UART_Transmitter_wave.do
# Created on: Tue Feb 12 04:09:58 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
