######################################################################
#
# File name : UART_Receiver_elaborate.do
# Created on: Thu Feb 14 02:04:16 +0200 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

quit -force
